# 文件大小限制
file_limits:
  max_upload_size: 1000  # MB
  max_file_size: 1000    # MB
  read_buffer_size: 4096

# 输出设置
output:
  filename: "combined_code.txt"

# API 密钥设置
api_keys:
  deepseek: ""  # 在此处填入你的 DeepSeek API 密钥
  github: ""    # 在此处填入你的 GitHub API 密钥（可选）

# 日志配置
logging:
  level: "debug"  # 可选值：debug, info, warn, error
  output_path: "./logs"

# 排除的目录前缀
excluded_dir_prefixes:
  - ".git/"
  - "node_modules/"
  - "vendor/"
  - "bin/"
  - "obj/"
  - "dist/"
  - "build/"
  - "target/"

# 排除的文件扩展名
excluded_extensions:
  - ".exe"
  - ".dll"
  - ".so"
  - ".dylib"
  - ".zip"
  - ".tar"
  - ".gz"
  - ".rar"
  - ".7z"
  - ".jar"
  - ".war"
  - ".ear"
  - ".class"
  - ".pyc"
  - ".pyo"
  - ".pyd"
  - ".obj"
  - ".o"
  - ".a"
  - ".lib"
  - ".png"
  - ".jpg"
  - ".jpeg"
  - ".gif"
  - ".bmp"
  - ".ico"
  - ".svg"
  - ".mp3"
  - ".mp4"
  - ".avi"
  - ".mov"
  - ".wmv"
  - ".flv"
  - ".swf"
  - ".pdf"
  - ".doc"
  - ".docx"
  - ".xls"
  - ".xlsx"
  - ".ppt"
  - ".pptx"

# 支持的文本文件扩展名
text_extensions:
  - ".txt"
  - ".md"
  - ".markdown"
  - ".rst"
  - ".go"
  - ".py"
  - ".js"
  - ".jsx"
  - ".ts"
  - ".tsx"
  - ".html"
  - ".htm"
  - ".css"
  - ".scss"
  - ".sass"
  - ".less"
  - ".json"
  - ".xml"
  - ".yaml"
  - ".yml"
  - ".ini"
  - ".conf"
  - ".cfg"
  - ".properties"
  - ".env"
  - ".sh"
  - ".bash"
  - ".zsh"
  - ".fish"
  - ".bat"
  - ".cmd"
  - ".ps1"
  - ".sql"
  - ".c"
  - ".h"
  - ".cpp"
  - ".hpp"
  - ".cs"
  - ".java"
  - ".rb"
  - ".php"
  - ".pl"
  - ".pm"
  - ".t"
  - ".swift"
  - ".kt"
  - ".kts"
  - ".rs"
  - ".r"
  - ".scala"
  - ".clj"
  - ".ex"
  - ".exs"
  - ".erl"
  - ".hrl"
  - ".hs"
  - ".lhs"
  - ".lua"
  - ".m"
  - ".mm"
  - ".proto"
  - ".vue"
  - ".elm"
  - ".fs"
  - ".fsx"
  - ".fsi"
  - ".fsscript"

# 无扩展名的文本文件名
text_filenames:
  - "Dockerfile"
  - "Makefile"
  - "README"
  - "LICENSE"
  - "CHANGELOG"
  - "CONTRIBUTING"
  - "AUTHORS"
  - "NOTICE"
  - ".gitignore"
  - ".dockerignore"
  - ".editorconfig"
  - ".eslintrc"
  - ".prettierrc"
  - ".babelrc"
  - ".npmrc"
  - ".yarnrc"
  - "go.mod"
  - "go.sum"
  - "requirements.txt"
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile"
  - "Gemfile.lock"
  - "composer.json"
  - "composer.lock"
  - "poetry.lock"
  - "pyproject.toml"

# 特殊 MIME 类型
text_mime_types:
  - "text/plain"
  - "text/html"
  - "text/css"
  - "text/javascript"
  - "text/xml"
  - "text/yaml"
  - "text/markdown"
  - "text/x-go"
  - "text/x-python"
  - "text/x-java"
  - "text/x-c"
  - "text/x-c++"
  - "text/x-csharp"
  - "text/x-ruby"
  - "text/x-php"
  - "text/x-perl"
  - "text/x-swift"
  - "text/x-kotlin"
  - "text/x-rust"
  - "text/x-scala"
  - "text/x-clojure"
  - "text/x-elixir"
  - "text/x-erlang"
  - "text/x-haskell"
  - "text/x-lua"
  - "text/x-objective-c"
  - "text/x-protobuf"
  - "text/x-vue"
  - "text/x-elm"
  - "text/x-fsharp" 