name: Direct Binary Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v ./...

    - name: Build Linux binary
      run: GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o repo-prompt-web main.go

    - name: Copy config file
      run: cp config.yml config.sample.yml

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "repo-prompt-web,config.sample.yml"
        target: "/www/wwwroot/repo-prompt-web/app"
        strip_components: 0

    - name: Setup service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          # 确保目录存在
          mkdir -p /www/wwwroot/repo-prompt-web/config
          mkdir -p /www/wwwroot/repo-prompt-web/logs
          
          # 如果配置文件不存在，复制示例配置
          if [ ! -f /www/wwwroot/repo-prompt-web/config/config.yml ]; then
            cp /www/wwwroot/repo-prompt-web/app/config.sample.yml /www/wwwroot/repo-prompt-web/config/config.yml
          fi
          
          # 确保可执行权限
          chmod +x /www/wwwroot/repo-prompt-web/app/repo-prompt-web
          
          # 创建systemd服务文件
          cat > /etc/systemd/system/repo-prompt-web.service << EOF
          [Unit]
          Description=Repo Prompt Web Service
          After=network.target
          
          [Service]
          Type=simple
          User=root
          WorkingDirectory=/www/wwwroot/repo-prompt-web/app
          ExecStart=/www/wwwroot/repo-prompt-web/app/repo-prompt-web
          Restart=on-failure
          RestartSec=5
          Environment=DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          Environment=GITHUB_API_KEY=${{ secrets.GH_API_KEY }}
          Environment=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          Environment=GEMINI_PROXY=${{ secrets.GEMINI_PROXY }}
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # 重新加载systemd配置
          systemctl daemon-reload
          
          # 启动或重启服务
          systemctl restart repo-prompt-web
          
          # 设置开机自启
          systemctl enable repo-prompt-web
          
          # 检查服务状态
          systemctl status repo-prompt-web 