name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/repo-prompt-web:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/repo-prompt-web:latest

  deploy-release:
    needs: [goreleaser, docker-release]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.PROD_DEPLOY_USERNAME }}
          key: ${{ secrets.PROD_DEPLOY_KEY }}
          port: 22
          script: |
            VERSION=${GITHUB_REF#refs/tags/}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/repo-prompt-web:$VERSION
            docker stop repo-prompt-web || true
            docker rm repo-prompt-web || true
            docker run -d --name repo-prompt-web \
              -p 8080:8080 \
              -e DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }} \
              -e GITHUB_API_KEY=${{ secrets.GH_API_KEY }} \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              -e GEMINI_PROXY=${{ secrets.GEMINI_PROXY }} \
              -v /www/wwwroot/repo-prompt-web/config:/app/config \
              -v /www/wwwroot/repo-prompt-web/logs:/app/logs \
              ${{ secrets.DOCKERHUB_USERNAME }}/repo-prompt-web:$VERSION